/**
 * Museums Meta Data - Lightweight listing for homepage
 * Auto-generated from data/museums-meta.json
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * To update: modify data/museums-meta.json and run:
 *   node tools/generate-museums-meta-js.js
 * 
 * This file provides lightweight metadata for homepage display.
 * Full museum details (collections, checklists) are loaded dynamically from KV Store.
 */

window.MUSEUMS_META = [
  {
    "id": "forbidden-city",
    "name": "故宫博物院",
    "location": "北京",
    "tags": [
      "历史",
      "建筑",
      "文物"
    ],
    "image": "https://museumcheck.cn/images/forbidden-city-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "清明上河图",
        "dynasty": "北宋",
        "category": "书画（风俗长卷）",
        "imageUrl": "https://museumcheck.cn/images/forbidden-city-t1-v1.jpg",
        "description": "北宋张择端所作风俗长卷，细致描绘汴京清明时节市井繁华与漕运景象，为中国十大传世名画之一，首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alongtheriver_QingMing.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "金瓯永固杯",
        "dynasty": "清乾隆",
        "category": "金银器（玉杯）",
        "imageUrl": "https://museumcheck.cn/images/forbidden-city-t2-v1.jpg",
        "description": "清乾隆御用饮酒金杯，金胎镶嵌珍珠、红蓝宝石，寓意江山永固，为清宫元旦开笔仪式之重器。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:金瓯永固杯_故宫珍宝馆.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "平复帖",
        "dynasty": "西晋",
        "category": "书法（章草）",
        "imageUrl": "https://museumcheck.cn/images/forbidden-city-t3-v1.jpg",
        "description": "西晋陆机章草墨迹，为现存最早的名人书法真迹，内容为一封问候友人的书札，首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:平复帖.png",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "乾隆田黄三联印",
        "dynasty": "清乾隆",
        "category": "玺印（田黄石）",
        "imageUrl": "https://museumcheck.cn/images/forbidden-city-t4-v1.jpg",
        "description": "清乾隆帝田黄三联玺，三方印以整块田黄石雕出的石链相连，巧夺天工，首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Qing_Jade_Seals,_Qianlong_Reign.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "九龙壁",
        "dynasty": "清乾隆",
        "category": "琉璃建筑",
        "imageUrl": "https://museumcheck.cn/images/forbidden-city-t5-v1.jpg",
        "description": "故宫珍宝馆内单面琉璃影壁，壁面九条蟠龙戏珠于云水山石之间，为清代琉璃烧造工艺代表作。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jiulongbi.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "大禹治水玉山",
        "dynasty": "清乾隆",
        "category": "玉器（玉山子）",
        "imageUrl": "",
        "description": "清乾隆青玉山子，重逾五吨，以宋人《大禹治水图》为稿本于扬州雕成，现存最大的单体玉雕，陈设于宁寿宫乐寿堂。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:大禹治水玉山.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 3.0",
    "imageCopyrightHolder": "User:kallgan",
    "imageAttribution": "User:kallgan / CC BY-SA 3.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3ASunset_of_the_Forbidden_City_2006.JPG"
  },
  {
    "id": "national-museum",
    "name": "中国国家博物馆",
    "location": "北京",
    "tags": [
      "历史",
      "文化",
      "艺术"
    ],
    "image": "https://museumcheck.cn/images/national-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "后母戊鼎",
        "dynasty": "商",
        "category": "青铜礼器",
        "imageUrl": "https://museumcheck.cn/images/national-museum-t1-v1.jpg",
        "description": "商代晚期青铜重器，重逾八百公斤，为现存最大最重的青铜礼器，1939年出土于河南安阳，首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:后母戊鼎.png",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "四羊方尊",
        "dynasty": "商",
        "category": "青铜礼器",
        "imageUrl": "https://museumcheck.cn/images/national-museum-t2-v1.jpg",
        "description": "商代晚期青铜礼器，四角各铸卷角羊首，造型雄奇，为商代青铜铸造工艺的巅峰之作。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Square_zun_with_four_sheep_01.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "击鼓说唱俑",
        "dynasty": "东汉",
        "category": "陶俑",
        "imageUrl": "https://museumcheck.cn/images/national-museum-t3-v1.jpg",
        "description": "东汉灰陶俳优俑，左抱扁鼓、右执鼓槌，神情诙谐，为汉代雕塑生动写实的杰出代表。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eastern_Han_Pottery_Storyteller_Figure.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "人面鱼纹彩陶盆",
        "dynasty": "新石器（仰韶文化）",
        "category": "彩陶",
        "imageUrl": "https://museumcheck.cn/images/national-museum-t4-v1.jpg",
        "description": "仰韶文化半坡类型典型器物，内壁绘人面鱼纹，1955年西安半坡遗址出土，体现先民的图腾与生命观念。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:人面鱼纹彩陶盆",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "大盂鼎",
        "dynasty": "西周",
        "category": "青铜礼器",
        "imageUrl": "https://museumcheck.cn/images/national-museum-t5-v1.jpg",
        "description": "西周康王时期青铜礼器，内壁291字铭文记康王对盂的诰命赏赐，书法浑厚，与上海博物馆大克鼎并称“海内双鼎”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Da_Yu_ding.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "金缕玉衣",
        "dynasty": "西汉",
        "category": "葬玉",
        "imageUrl": "https://museumcheck.cn/images/national-museum-t6-v1.jpg",
        "description": "汉代诸侯王葬服，以金丝缀连玉片而成，徐州狮子山楚王墓出土，体现汉代玉敛葬的等级与礼制。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:金缕玉衣_狮子山汉墓.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 3.0",
    "imageCopyrightHolder": "Temlsth",
    "imageAttribution": "Temlsth / CC BY-SA 3.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E4%B8%AD%E5%9B%BD%E5%9B%BD%E5%AE%B6%E5%8D%9A%E7%89%A9%E9%A6%86.JPG"
  },
  {
    "id": "shanghai-museum",
    "name": "上海博物馆",
    "location": "上海",
    "tags": [
      "艺术",
      "文物",
      "收藏"
    ],
    "image": "https://museumcheck.cn/images/shanghai-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "大克鼎",
        "dynasty": "西周",
        "category": "青铜礼器",
        "imageUrl": "https://museumcheck.cn/images/shanghai-museum-t1-v1.jpg",
        "description": "西周中期青铜礼器，内壁290字铭文记贵族克受周王赏赐而作器，为上博镇馆之宝，与国博大盂鼎并称“海内双鼎”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Da_Ke_ding.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "晋侯稣钟",
        "dynasty": "西周",
        "category": "青铜乐器",
        "imageUrl": "https://museumcheck.cn/images/shanghai-museum-t2-v1.jpg",
        "description": "西周晋侯稣编钟，钟上铭文记晋侯稣随周厉王出征获胜受赏，为上博镇馆之宝，是研究西周史与乐律的稀有实物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bells_of_Marquis_Su_of_Jin.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "商鞅方升",
        "dynasty": "战国",
        "category": "量器",
        "imageUrl": "https://museumcheck.cn/images/shanghai-museum-t3-v1.jpg",
        "description": "战国商鞅变法时制造的标准量器，刻有铭文，为秦国统一度量衡的实物见证，是中国度量衡史的重要物证。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:商鞅方升",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "王献之鸭头丸帖",
        "dynasty": "东晋",
        "category": "书法（行草）",
        "imageUrl": "https://museumcheck.cn/images/shanghai-museum-t4-v1.jpg",
        "description": "东晋王献之传世行草墨迹，帖文仅“鸭头丸故不佳”等十五字，笔势连绵，为禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:王献之_行书鸭头丸帖卷",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "淳化阁帖",
        "dynasty": "北宋",
        "category": "法帖（刻帖）",
        "imageUrl": "https://museumcheck.cn/images/shanghai-museum-t5-v1.jpg",
        "description": "北宋《淳化秘阁法帖》传世最善本（修内司本），汇刻历代名家书迹，素有“法帖之祖”之称。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:淳化阁帖",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "越窑青釉海棠式碗",
        "dynasty": "唐",
        "category": "瓷器（越窑青瓷）",
        "imageUrl": "https://museumcheck.cn/images/shanghai-museum-t6-v1.jpg",
        "description": "唐代越窑青釉碗，海棠式曲线口腹，釉色青润，为越窑秘色瓷代表作，体现唐代越窑素雅之美。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:越窑青釉海棠式碗",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 4.0",
    "imageCopyrightHolder": "Hpppp0527",
    "imageAttribution": "Hpppp0527 / CC BY-SA 4.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E4%B8%8A%E6%B5%B7%E5%8D%9A%E7%89%A9%E9%A6%86%E4%B8%9C%E9%A6%86_161003.jpg"
  },
  {
    "id": "shanghai-natural-history-museum",
    "name": "上海自然博物馆",
    "location": "上海",
    "tags": [
      "自然科学",
      "生物多样性",
      "古生物"
    ],
    "image": "",
    "hasCollections": true,
    "level": null
  },
  {
    "id": "terracotta-warriors",
    "name": "秦始皇帝陵博物院",
    "location": "西安",
    "tags": [
      "历史",
      "考古",
      "世界遗产"
    ],
    "image": "https://museumcheck.cn/images/qinling-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "秦陵二号铜车马（安车）",
        "dynasty": "秦代",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/qinling-erhaotongchema-v1.jpg",
        "description": "1980年出土于秦始皇陵封土西侧，按真车1/2比例铸造，由三千多个零件组成，工艺精湛，被誉为'青铜之冠'，属首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Qin_bronze_chariot_two.jpg",
        "rightsType": "CC",
        "license": "CC BY 3.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "Jmhullot, CC BY 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "跪射俑",
        "dynasty": "秦代",
        "category": "陶俑",
        "imageUrl": "https://museumcheck.cn/images/qinling-guisheyong-v1.jpg",
        "description": "出土于二号坑，单膝跪地、双手在右侧作持弓状，姿态稳定不易坍塌，是兵马俑中保存最完整的陶俑之一，鞋底针脚纹路清晰可见。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kneeling_archer_of_the_Terracotta_Army.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "Difference engine, CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "将军俑",
        "dynasty": "秦代",
        "category": "陶俑",
        "imageUrl": "https://museumcheck.cn/images/qinling-jiangjunyong-v1.jpg",
        "description": "兵马俑中级别最高的陶俑，头戴鹖冠、身披彩绘鱼鳞甲，昂首挺胸、神态沉稳，出土于一号坑，展现秦军高级将领的威严。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:2009_Qin_Terracotta_General.jpg",
        "rightsType": "CC0",
        "license": "CC0 1.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "Gary Todd, CC0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 3.0",
    "imageCopyrightHolder": "Ghost Barney",
    "imageAttribution": "Ghost Barney / CC BY-SA 3.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3AEmperor_Qinshihuang%27s_Mausoleum_Site_Museum.jpg"
  },
  {
    "id": "nanjing-museum",
    "name": "南京博物院",
    "location": "南京",
    "tags": [
      "历史",
      "艺术",
      "民俗"
    ],
    "image": "https://museumcheck.cn/images/nanjing-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "金兽",
        "dynasty": "西汉",
        "category": "金银器（金器）",
        "imageUrl": "https://museumcheck.cn/images/nanjing-museum-t1-v1.jpg",
        "description": "1982年江苏盱眙南窑庄窖藏出土，西汉，重达9100克，是迄今考古发现最重的一块金器；造型为伏卧状豹形神兽，南京博物院镇馆之宝。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gold_Beast,_Nanjing_Museum.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "竹林七贤与荣启期砖画",
        "dynasty": "南朝",
        "category": "砖画（墓葬壁画）",
        "imageUrl": "https://museumcheck.cn/images/nanjing-museum-t2-v1.jpg",
        "description": "1960年南京西善桥宫山墓出土，南朝，由200余块模印画像砖拼嵌而成，表现嵇康、阮籍等竹林七贤与荣启期，是我国最早的魏晋名士图卷，首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Seven_Sages_of_the_Bamboo_Grove_1.Nanjing_Museum.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "青釉神兽尊",
        "dynasty": "西晋",
        "category": "瓷器（青釉）",
        "imageUrl": "https://museumcheck.cn/images/nanjing-museum-t3-v1.jpg",
        "description": "1976年江苏宜兴周处家族墓出土，西晋，高27.9厘米，以青釉瓷塑成神兽形，是西晋青瓷塑贴工艺的代表作，南京博物院藏。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Celadon-glazed_porcelain_Zun_with_design_of_a_monster_01.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 2.5",
    "imageCopyrightHolder": "Farm",
    "imageAttribution": "Farm / CC BY-SA 2.5, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3ANanjing_Museum_big.jpg"
  },
  {
    "id": "hubei-museum",
    "name": "湖北省博物馆",
    "location": "武汉",
    "tags": [
      "历史",
      "音乐",
      "青铜器"
    ],
    "image": "https://museumcheck.cn/images/hubei-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "曾侯乙编钟",
        "dynasty": "战国早期",
        "category": "青铜乐器",
        "imageUrl": "https://museumcheck.cn/images/hubei-museum-t1-v1.jpg",
        "description": "战国早期曾国国君墓葬出土，65件青铜编钟总重超2.5吨，一钟双音、音域宽广，改写了世界音乐史，首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bianzhong_of_Marquis_Yi_of_Zeng_Wuhan.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "越王勾践剑",
        "dynasty": "春秋晚期",
        "category": "青铜兵器",
        "imageUrl": "https://museumcheck.cn/images/hubei-museum-t2-v1.jpg",
        "description": "春秋晚期越王勾践自用青铜剑，剑身满饰菱形暗格花纹，深埋两千余年仍寒光逼人、几无锈蚀，被誉为“天下第一剑”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:20230208_Bronze_sword_used_by_King_Goujian_of_Yue_01.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "曾侯乙尊盘",
        "dynasty": "战国早期",
        "category": "青铜礼器",
        "imageUrl": "https://museumcheck.cn/images/hubei-museum-t3-v1.jpg",
        "description": "战国早期，由尊与盘组成，通体失蜡法铸造的镂空蟠螭纹极尽繁复，是先秦青铜铸造工艺的巅峰之作。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:曾侯乙尊盘，2015-04-06_01.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "云梦睡虎地秦简",
        "dynasty": "秦",
        "category": "竹简（法律文献）",
        "imageUrl": "https://museumcheck.cn/images/hubei-museum-t4-v1.jpg",
        "description": "秦代竹简，含《秦律十八种》等法律文献，出自基层官吏“喜”的墓葬，是了解秦代制度与日常的一手史料。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bamboo_Slips_of_Qin_Dynasty_Unearthed_from_Shuihudi_2013-01.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "元青花四爱图梅瓶",
        "dynasty": "元",
        "category": "瓷器（青花）",
        "imageUrl": "https://museumcheck.cn/images/hubei-museum-t5-v1.jpg",
        "description": "元代青花瓷代表作，腹部绘王羲之爱兰、陶渊明爱菊、周敦颐爱莲、林逋爱梅鹤“四爱图”，2006年出自明郢靖王墓。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:元青花四爱图梅瓶.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "鹿角立鹤",
        "dynasty": "战国早期",
        "category": "青铜（神兽造型）",
        "imageUrl": "https://museumcheck.cn/images/hubei-museum-t6-v1.jpg",
        "description": "战国早期曾侯乙墓出土，青铜铸鹤身、鹿角立于鹤首，造型奇特的祥瑞神兽，象征沟通天地。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:鹿角立鹤.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 3.0",
    "imageCopyrightHolder": "No machine-readable author provided. 风之清扬 assumed (based on copyright claims).",
    "imageAttribution": "No machine-readable author provided. 风之清扬 assumed (based on copyright claims). / CC BY-SA 3.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3AHubei_Provincial_Museum.JPG"
  },
  {
    "id": "shaanxi-history",
    "name": "陕西历史博物馆",
    "location": "西安",
    "tags": [
      "历史",
      "文物",
      "古代文明"
    ],
    "image": "https://museumcheck.cn/images/shaanxi-history-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "镶金兽首玛瑙杯",
        "dynasty": "唐代",
        "category": "玉器（玛瑙）",
        "imageUrl": "https://museumcheck.cn/images/shaanxi-history-t1-v1.jpg",
        "description": "1970年西安南郊何家村窖藏出土，长15.5厘米，兽首牛角形玛瑙杯，迄今所见唐代唯一俏色雕琢的玛瑙艺术珍品，陕西历史博物馆镇馆之宝、首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:唐-玛瑙兽首杯.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "唐三彩载乐骆驼俑",
        "dynasty": "唐代",
        "category": "三彩陶器",
        "imageUrl": "https://museumcheck.cn/images/shaanxi-history-t2-v1.jpg",
        "description": "唐代，高58厘米，骆驼背驮平台上有7名乐俑奏乐歌唱，是唐三彩中罕见的盛唐乐舞题材代表作。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tang_Sancai_Porcelain-_Musicians_on_a_Camel.jpg",
        "rightsType": "CC0",
        "license": "CC0",
        "copyrightHolder": "Gary Todd (Wikimedia Commons)",
        "attribution": "Gary Todd / CC0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "鸳鸯莲瓣纹金碗",
        "dynasty": "唐代",
        "category": "金银器",
        "imageUrl": "https://museumcheck.cn/images/shaanxi-history-t3-v1.jpg",
        "description": "1970年何家村窖藏出土，高5.5厘米，捶揲成型的金碗外壁錾刻鸳鸯、莲瓣等纹样，唐代金银器工艺巅峰之作。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:鸳鸯莲瓣纹金碗_20091112.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 3.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "CC BY-SA 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 4.0",
    "imageCopyrightHolder": "Liuxingy",
    "imageAttribution": "Liuxingy / CC BY-SA 4.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E9%99%95%E8%A5%BF%E5%8E%86%E5%8F%B2%E5%8D%9A%E7%89%A9%E9%A6%86.jpg"
  },
  {
    "id": "suzhou-museum",
    "name": "苏州博物馆",
    "location": "苏州",
    "tags": [
      "艺术",
      "建筑",
      "江南文化"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Suzhou_Museum_-_new_buildings.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhejiang-museum",
    "name": "浙江省博物馆",
    "location": "杭州",
    "tags": [
      "历史",
      "文化",
      "江南"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d0/%E6%B5%99%E6%B1%9F%E7%9C%81%E5%8D%9A%E7%89%A9%E9%A6%86_-_panoramio.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "guangdong-museum",
    "name": "广东省博物馆",
    "location": "广州",
    "tags": [
      "岭南文化",
      "海丝",
      "文物"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Guangdong_Museum.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "sichuan-museum",
    "name": "四川博物院",
    "location": "成都",
    "tags": [
      "巴蜀文化",
      "历史",
      "民俗"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5f/%E5%9B%9B%E5%B7%9D%E5%8D%9A%E7%89%A9%E9%99%A2.JPG",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "henan-museum",
    "name": "河南博物院",
    "location": "郑州",
    "tags": [
      "中原文化",
      "文物",
      "历史"
    ],
    "image": "https://museumcheck.cn/images/henan-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "妇好鸮尊",
        "dynasty": "商代晚期",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/henan-museum-t1-v1.jpg",
        "description": "1976年安阳殷墟妇好墓出土，通高46.3厘米，鸮（猫头鹰）形青铜盛酒器，中国最早鸟形铜尊之一，河南博物院镇院之宝。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fuhao_Owl_Zun_front.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Cangmin (Wikimedia Commons)",
        "attribution": "Cangmin / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "莲鹤方壶",
        "dynasty": "春秋中期",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/henan-museum-t2-v1.jpg",
        "description": "1923年新郑李家楼郑公大墓出土，高117厘米，壶顶莲瓣盛开、立一振翅仙鹤，郭沫若誉其为'时代精神之象征'；河南博物院与故宫各藏一件。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:河南博物院藏莲鹤方壶.jpg",
        "rightsType": "CC",
        "license": "CC BY 3.0",
        "copyrightHolder": "Greg_kf (Wikimedia Commons)",
        "attribution": "Greg_kf / CC BY 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "云纹铜禁",
        "dynasty": "春秋中期",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/henan-museum-t3-v1.jpg",
        "description": "1978年淅川下寺楚墓出土，通高28.8厘米，失蜡法铸造的云纹铜禁（承置酒器的案具），中国首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bronze_jin_from_Henan.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 3.0",
        "copyrightHolder": "Greg_kf (Wikimedia Commons)",
        "attribution": "Greg_kf / CC BY-SA 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 4.0",
    "imageCopyrightHolder": "Windmemories",
    "imageAttribution": "Windmemories / CC BY-SA 4.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3A20210220_Henan_Museum_-_main_hall_01.jpg"
  },
  {
    "id": "liaoning-museum",
    "name": "辽宁省博物馆",
    "location": "沈阳",
    "tags": [
      "东北文化",
      "考古",
      "历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shandong-museum",
    "name": "山东博物馆",
    "location": "济南",
    "tags": [
      "齐鲁文化",
      "孔子",
      "历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "tianjin-museum",
    "name": "天津博物馆",
    "location": "天津",
    "tags": [
      "历史",
      "青铜器",
      "书画",
      "瓷器",
      "非遗",
      "天津"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/%E5%A4%A9%E6%B4%A5%E5%8D%9A%E7%89%A9%E9%A6%86.png/960px-%E5%A4%A9%E6%B4%A5%E5%8D%9A%E7%89%A9%E9%A6%86.png",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "china-art-museum",
    "name": "中国美术馆",
    "location": "北京",
    "tags": [
      "美术",
      "艺术",
      "绘画"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "tibet-museum",
    "name": "西藏博物馆",
    "location": "拉萨",
    "tags": [
      "藏族文化",
      "雪域高原",
      "佛教"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "xinjiang-museum",
    "name": "新疆维吾尔自治区博物馆",
    "location": "乌鲁木齐",
    "tags": [
      "丝绸之路",
      "多民族",
      "西域文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yunnan-museum",
    "name": "云南省博物馆",
    "location": "昆明",
    "tags": [
      "多民族",
      "西南文化",
      "边疆历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "inner-mongolia-museum",
    "name": "内蒙古博物院",
    "location": "呼和浩特",
    "tags": [
      "草原文化",
      "蒙古族",
      "游牧文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "chongqing-three-gorges-museum",
    "name": "重庆中国三峡博物馆",
    "location": "重庆",
    "tags": [
      "三峡文化",
      "巴渝文化",
      "山城历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "qinghai-museum",
    "name": "青海省博物馆",
    "location": "西宁",
    "tags": [
      "青藏高原",
      "多民族",
      "高原文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "heilongjiang-museum",
    "name": "黑龙江省博物馆",
    "location": "哈尔滨",
    "tags": [
      "东北文化",
      "中俄交流",
      "近代史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-capital-museum",
    "name": "首都博物馆",
    "location": "北京",
    "tags": [
      "北京历史",
      "古都文化",
      "民俗"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/36/Capital_Museum_in_Beijing.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-military-museum",
    "name": "中国人民革命军事博物馆",
    "location": "北京",
    "tags": [
      "军事历史",
      "革命历史",
      "国防教育"
    ],
    "image": "https://img1.baidu.com/it/u=4286222987,673276445&fm=253&fmt=auto&app=138?f=JPEG?w=800&h=1067",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-natural-history-museum",
    "name": "国家自然博物馆",
    "location": "北京",
    "tags": [
      "自然科学",
      "生物进化",
      "古生物"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Beijing_Museum_of_Natural_History_2.jpg",
    "hasCollections": true,
    "level": null
  },
  {
    "id": "china-railway-museum",
    "name": "中国铁道博物馆",
    "location": "北京",
    "tags": [
      "铁路历史",
      "交通运输",
      "工业发展"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-planetarium",
    "name": "北京天文馆",
    "location": "北京",
    "tags": [
      "天文科学",
      "宇宙探索",
      "科普教育"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Beijing_Planetarium_%2820221112164636%29.jpg/1280px-Beijing_Planetarium_%2820221112164636%29.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "shanghai-science-technology-museum",
    "name": "上海科技馆",
    "location": "上海",
    "tags": [
      "科技创新",
      "科学教育",
      "互动体验"
    ],
    "image": "https://museumcheck.cn/images/shanghai-science-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "风云二号气象卫星模型",
        "dynasty": "现代",
        "category": "航天展项",
        "imageUrl": "https://museumcheck.cn/images/shanghai-science-museum-fengyun2-v1.jpg",
        "description": "「宇航天地」展区陈列的风云二号气象卫星模型。风云二号是中国自主研制的地球静止轨道气象卫星，该展项直观展示了中国航天与气象观测技术成就。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:20090829_Model_of_Fengyun-2_4002.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "Jakub Hałun, CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "弹钢琴机器人",
        "dynasty": "现代",
        "category": "机器人展项",
        "imageUrl": "https://museumcheck.cn/images/shanghai-science-museum-robot-v1.jpg",
        "description": "「机器人世界」展区的标志性展项——能现场演奏钢琴曲的机器人，长期是馆内人气最高的打卡点之一，展示机器人机电一体化与控制技术。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:20090829_Robot_in_Shanghai_Science_and_Technology_Museum_3985.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "Jakub Hałun, CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "大象模型",
        "dynasty": "现代",
        "category": "自然展项",
        "imageUrl": "https://museumcheck.cn/images/shanghai-science-museum-elephant-v1.jpg",
        "description": "馆内自然生态展项中的大象标本模型，还原野生动物生存场景，传递生物多样性与生态保护理念。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elephant_model_at_Shanghai_Science_and_Technology_Museum-20130322.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Wikimedia Commons",
        "attribution": "Shwangtianyuan, CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC0",
    "imageCopyrightHolder": "DvTor8303",
    "imageAttribution": "DvTor8303 / CC0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3AShanghai_Science_and_Technology_Museum_glass_sphere_20260418.jpg"
  },
  {
    "id": "guangzhou-museum",
    "name": "广州博物馆",
    "location": "广州",
    "tags": [
      "岭南文化",
      "广州历史",
      "海上丝绸之路"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shenzhen-museum",
    "name": "深圳博物馆",
    "location": "深圳",
    "tags": [
      "改革开放",
      "城市发展",
      "现代化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "xian-museum",
    "name": "西安博物院",
    "location": "西安",
    "tags": [
      "古都文化",
      "丝绸之路",
      "唐文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "chengdu-jinsha-museum",
    "name": "成都金沙遗址博物馆",
    "location": "成都",
    "tags": [
      "古蜀文明",
      "考古发现",
      "金沙文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanjing-massacre-memorial",
    "name": "侵华日军南京大屠杀遇难同胞纪念馆",
    "location": "南京",
    "tags": [
      "历史教育",
      "爱国主义",
      "和平教育"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "hangzhou-museum",
    "name": "杭州博物馆",
    "location": "杭州",
    "tags": [
      "西湖文化",
      "江南文化",
      "杭州历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "ningbo-museum",
    "name": "宁波博物馆",
    "location": "宁波",
    "tags": [
      "海洋文化",
      "港口贸易",
      "商业历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "wuxi-museum",
    "name": "无锡博物院",
    "location": "无锡",
    "tags": [
      "江南文化",
      "水乡文化",
      "民族工业"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "changzhou-museum",
    "name": "常州博物馆",
    "location": "常州",
    "tags": [
      "常州历史",
      "江南文化",
      "现代发展"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yangzhou-museum",
    "name": "扬州博物馆",
    "location": "扬州",
    "tags": [
      "运河文化",
      "盐商文化",
      "园林艺术"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "hefei-museum",
    "name": "安徽博物院",
    "location": "合肥",
    "tags": [
      "徽文化",
      "安徽历史",
      "新安文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanchang-museum",
    "name": "江西省博物馆",
    "location": "南昌",
    "tags": [
      "赣文化",
      "江西历史",
      "陶瓷文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jinan-museum",
    "name": "济南市博物馆",
    "location": "济南",
    "tags": [
      "泉城文化",
      "齐鲁文化",
      "济南历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "qingdao-museum",
    "name": "青岛市博物馆",
    "location": "青岛",
    "tags": [
      "海洋文化",
      "青岛历史",
      "近代建筑"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhengzhou-museum",
    "name": "郑州博物馆",
    "location": "郑州",
    "tags": [
      "中原文化",
      "商代文明",
      "黄河文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "wuhan-museum",
    "name": "武汉博物馆",
    "location": "武汉",
    "tags": [
      "荆楚文化",
      "武汉历史",
      "长江文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "kunming-museum",
    "name": "昆明市博物馆",
    "location": "昆明",
    "tags": [
      "滇文化",
      "民族文化",
      "春城文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "guiyang-museum",
    "name": "贵州省博物馆",
    "location": "贵阳",
    "tags": [
      "多民族文化",
      "贵州历史",
      "山地文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "fuzhou-museum",
    "name": "福建博物院",
    "location": "福州",
    "tags": [
      "闽文化",
      "海洋文化",
      "侨乡文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanning-museum",
    "name": "广西壮族自治区博物馆",
    "location": "南宁",
    "tags": [
      "壮族文化",
      "民族文化",
      "桂文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "haikou-museum",
    "name": "海南省博物馆",
    "location": "海口",
    "tags": [
      "海岛文化",
      "热带文化",
      "海南历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shijiazhuang-museum",
    "name": "河北博物院",
    "location": "石家庄",
    "tags": [
      "燕赵文化",
      "河北历史",
      "中山国"
    ],
    "image": "https://museumcheck.cn/images/shijiazhuang-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "长信宫灯",
        "dynasty": "西汉",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/shijiazhuang-museum-t1-v1.jpg",
        "description": "西汉青铜器，1968年河北满城窦绾墓出土，高48厘米，通体鎏金。作跪地执灯宫女形：灯盘可转动，灯罩屏板可推合以调节亮度与照射方向；宫女右臂中空为烟道，烟灰经衣袖进入体中以保持室内清洁。灯分头、身、右臂、灯座、灯盘、灯罩六部分，均可拆卸清洗，灯体刻“长信尚浴”“阳信家”等铭文65字。被誉为“中华第一灯”，2002年列入首批禁止出境展览文物名录，河北博物院“镇馆之宝”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%95%BF%E4%BF%A1%E5%AE%AB%E7%81%AF-%E6%B2%B3%E5%8C%97%E5%8D%9A%E7%89%A9%E9%99%A2.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Suginami",
        "attribution": "Suginami / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "刘胜金缕玉衣",
        "dynasty": "西汉",
        "category": "玉器",
        "imageUrl": "https://museumcheck.cn/images/shijiazhuang-museum-t2-v1.jpg",
        "description": "西汉玉衣，1968年河北满城汉墓（中山靖王刘胜墓）出土。由2498片玉片、约1100克金丝编缀而成，是我国考古发掘中年代最早、保存最完整、规格最高的汉代金缕玉衣，再现了汉代诸侯王丧葬礼制与玉作工艺的巅峰。2002年列入首批禁止出境展览文物名录，河北博物院“镇馆之宝”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jade_burial_suit_of_Liu_Sheng.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Baomi",
        "attribution": "Baomi / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "错金银四龙四凤铜方案座",
        "dynasty": "战国",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/shijiazhuang-museum-t3-v1.jpg",
        "description": "战国青铜器，1977年河北平山三汲村中山王墓出土。案面已朽，仅存案座，边长47.5厘米。底部两雄两雌跪鹿承托，四龙四凤盘绕纠结组成案身：四龙独首双尾上托斗拱，四凤双翅聚于中央连成半球，凤头自龙尾引颈而出。集铸造、镶嵌、焊接等多种工艺于一身，复杂精巧，是战国中山国青铜工艺的代表作，河北博物院“十大珍宝”之一（首批禁止出境展览文物）。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bronze_Square_Table_Stand_Decorated_with_Dragon-and-phoenix.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Photographed by Baomi",
        "attribution": "Photographed by Baomi / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 4.0",
    "imageCopyrightHolder": "Windmemories",
    "imageAttribution": "Windmemories / CC BY-SA 4.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3A20250118_Hebei_Museum.jpg"
  },
  {
    "id": "taiyuan-museum",
    "name": "山西博物院",
    "location": "太原",
    "tags": [
      "晋文化",
      "煤炭文化",
      "古建筑"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "hohhot-museum",
    "name": "内蒙古自然博物馆",
    "location": "呼和浩特",
    "tags": [
      "草原文化",
      "自然生态",
      "蒙古族文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "lanzhou-museum",
    "name": "甘肃省博物馆",
    "location": "兰州",
    "tags": [
      "丝路文化",
      "马踏飞燕",
      "敦煌文化"
    ],
    "image": "https://museumcheck.cn/images/lanzhou-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "铜奔马（马踏飞燕）",
        "dynasty": "东汉",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/lanzhou-museum-t1-v1.jpg",
        "description": "东汉青铜器，1969年出土于甘肃武威雷台汉墓。通高34.5厘米、长45厘米、宽13.1厘米、重7.3千克。作骏马昂首嘶鸣、疾足奔驰状，三足腾空，一足踏掠飞鸟（燕），摄取奔马超越飞鸟的一瞬；全身着力点集注于踏鸟一足之上，精确掌握力学平衡原理，工艺卓绝。1983年被确定为中国旅游标志，1986年鉴定为国宝级文物，2002年列入首批禁止出境展览文物名录，是丝绸之路精神的象征、甘肃省博物馆“镇馆之宝”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%9B%B7%E5%8F%B0%E6%B1%89%E5%A2%93%E9%93%9C%E5%A5%94%E9%A9%AC3.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "三猎",
        "attribution": "三猎 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "人头形器口彩陶瓶",
        "dynasty": "新石器时代（仰韶文化）",
        "category": "彩陶",
        "imageUrl": "https://museumcheck.cn/images/lanzhou-museum-t2-v1.jpg",
        "description": "仰韶文化中期（庙底沟类型）彩陶，1973年出土于甘肃秦安大地湾遗址。高32.3厘米、口径4厘米、底径6.8厘米，细泥红陶质地。瓶口雕塑为圆雕人头像：挺鼻小嘴、齐刘海、双耳有系挂饰物小孔；瓶身绘黑彩弧线三角纹与变体鸟纹。是大地湾出土上千件陶器中唯一塑有人像的彩陶瓶，将人头与葫芦瓶巧妙结合，体现先民对自身力量的认识与艺术再现能力。2013年列入第三批禁止出境展览文物名录。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E4%BB%B0%E9%9F%B6%E6%96%87%E5%8C%96%E4%BA%BA%E5%A4%B4%E5%BD%A2%E5%99%A8%E5%8F%A3%E5%BD%A9%E9%99%B6%E7%93%B6.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "三猎",
        "attribution": "三猎 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "莲花玻璃托盏",
        "dynasty": "元",
        "category": "玻璃器",
        "imageUrl": "https://museumcheck.cn/images/lanzhou-museum-t3-v1.jpg",
        "description": "元代玻璃器，出土于甘肃漳县汪世显家族墓。一托一盏，通体半透明蓝色玻璃质，仿莲花造型——托如莲叶，盏似盛开的莲花，是国内迄今出土最完整的一套元代玻璃托盏。造型清丽、工艺精巧，反映了元代玻璃制造工艺的高超水平，是甘肃省博物馆馆藏精品。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yuan_Lotus-shaped_Glass_Calix_(10096176946).jpg",
        "rightsType": "CC",
        "license": "CC0",
        "copyrightHolder": "Gary Todd",
        "attribution": "Gary Todd / CC0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 2.0",
    "imageCopyrightHolder": "Caitriana Nicholson from 北京 ~ Beijing, 中国 ~ China",
    "imageAttribution": "Caitriana Nicholson from 北京 ~ Beijing, 中国 ~ China / CC BY-SA 2.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3AGansu_Provincial_Museum_-_%E7%94%98%E8%82%83%E7%9C%81%E5%8D%9A%E7%89%A9%E9%A6%86_%2817143542340%29.jpg"
  },
  {
    "id": "xining-museum",
    "name": "青海藏医药文化博物馆",
    "location": "西宁",
    "tags": [
      "藏医药",
      "高原文化",
      "民族医学"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yantai-museum",
    "name": "烟台市博物馆",
    "location": "烟台",
    "tags": [
      "胶东文化",
      "海洋文化",
      "近代开埠"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "linyi-museum",
    "name": "临沂市博物馆",
    "location": "临沂",
    "tags": [
      "沂蒙文化",
      "革命文化",
      "临沂历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "wenzhou-museum",
    "name": "温州博物馆",
    "location": "温州",
    "tags": [
      "瓯越文化",
      "商业文化",
      "温州历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shaoxing-museum",
    "name": "绍兴博物馆",
    "location": "绍兴",
    "tags": [
      "水乡文化",
      "越文化",
      "文人文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jiaxing-museum",
    "name": "嘉兴博物馆",
    "location": "嘉兴",
    "tags": [
      "红船精神",
      "江南文化",
      "嘉兴历史"
    ],
    "image": "https://museumcheck.cn/images/jiaxing-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "玉玦",
        "dynasty": "马家浜文化（约前5000–前4000）",
        "category": "玉器",
        "imageUrl": "https://museumcheck.cn/images/jiaxing-museum-t1-v1.jpg",
        "description": "马家浜文化玉玦，距今约七千年，中国最早的玉耳饰之一，见证长江下游玉文化的萌发。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Majiabang_Culture_Jade_Jue.jpg",
        "rightsType": "CC",
        "license": "CC0",
        "copyrightHolder": "Gary Todd",
        "attribution": "Gary Todd / CC0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "玉璜",
        "dynasty": "马家浜文化",
        "category": "玉器",
        "imageUrl": "https://museumcheck.cn/images/jiaxing-museum-t2-v1.jpg",
        "description": "马家浜文化玉璜，佩饰类玉礼器雏形，体现先民对玉的尊崇与审美。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Beiyinyangying_Culture_Agate_Huang_%26_Majiabang_Culture_Jade_Huang.jpg",
        "rightsType": "CC",
        "license": "CC0",
        "copyrightHolder": "Gary Todd",
        "attribution": "Gary Todd / CC0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "兽面形陶器耳",
        "dynasty": "马家浜文化",
        "category": "陶器",
        "imageUrl": "https://museumcheck.cn/images/jiaxing-museum-t3-v1.jpg",
        "description": "马家浜遗址出土的兽面形陶器耳，器物附件塑成兽面，憨态可掬，是马家浜陶器的特色。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Animal-faced_Pottery_Handle_01_2017-04.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 4.0",
    "imageCopyrightHolder": "Augoustoshai",
    "imageAttribution": "Augoustoshai / CC BY-SA 4.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E5%98%89%E5%85%B4%E5%8D%9A%E7%89%A9%E9%A6%86163043.jpg"
  },
  {
    "id": "jingdezhen-museum",
    "name": "景德镇中国陶瓷博物馆",
    "location": "景德镇",
    "tags": [
      "陶瓷文化",
      "制瓷工艺",
      "瓷都文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "quanzhou-museum",
    "name": "泉州海外交通史博物馆",
    "location": "泉州",
    "tags": [
      "海上丝绸之路",
      "海外交通",
      "泉州文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "quanzhou-huaqiao-museum",
    "name": "泉州华侨历史博物馆",
    "location": "泉州",
    "tags": [
      "华侨历史",
      "文化遗产",
      "泉州文化",
      "海外华人",
      "历史"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/dd/%E6%B3%89%E5%B7%9E%E5%8D%8E%E4%BE%A8%E5%8E%86%E5%8F%B2%E5%8D%9A%E7%89%A9%E9%A6%86.jpg",
    "hasCollections": true,
    "level": "三级"
  },
  {
    "id": "quanzhou-city-museum",
    "name": "泉州博物馆",
    "location": "泉州",
    "tags": [
      "历史",
      "文化",
      "闽南文化",
      "考古",
      "海丝文化"
    ],
    "image": "https://img2.baidu.com/it/u=3862590014,3235502598&fm=253&fmt=auto&app=138&f=JPEG&w=889&h=500",
    "hasCollections": false,
    "level": "二级"
  },
  {
    "id": "xiamen-museum",
    "name": "厦门市博物馆",
    "location": "厦门",
    "tags": [
      "闽南文化",
      "侨乡文化",
      "海岛文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jiangmen-museum",
    "name": "江门市博物馆",
    "location": "江门",
    "tags": [
      "侨乡文化",
      "碉楼文化",
      "江门历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "baotou-museum",
    "name": "包头博物馆",
    "location": "包头",
    "tags": [
      "工业文化",
      "草原文化",
      "钢铁文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yichang-museum",
    "name": "宜昌博物馆",
    "location": "宜昌",
    "tags": [
      "三峡文化",
      "长江文明",
      "水利文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "luoyang-museum",
    "name": "洛阳博物馆",
    "location": "洛阳",
    "tags": [
      "古都文化",
      "洛阳历史",
      "牡丹文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jingzhou-museum",
    "name": "荆州博物馆",
    "location": "荆州",
    "tags": [
      "楚文化",
      "历史名城",
      "文物考古"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "guilin-museum",
    "name": "桂林博物馆",
    "location": "桂林",
    "tags": [
      "山水文化",
      "桂北文化",
      "世界遗产"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jian-museum",
    "name": "吉安市博物馆",
    "location": "吉安",
    "tags": [
      "庐陵文化",
      "吉安历史",
      "书院文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shangrao-museum",
    "name": "上饶市博物馆",
    "location": "上饶",
    "tags": [
      "赣东北文化",
      "上饶历史",
      "生态文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "ganzhou-museum",
    "name": "赣州市博物馆",
    "location": "赣州",
    "tags": [
      "客家文化",
      "赣州历史",
      "宋城文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jiujiang-museum",
    "name": "九江市博物馆",
    "location": "九江",
    "tags": [
      "庐山文化",
      "九江历史",
      "长江文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-art-museum",
    "name": "北京艺术博物馆",
    "location": "北京",
    "tags": [
      "艺术",
      "绘画",
      "雕塞"
    ],
    "image": "https://img1.baidu.com/it/u=486738805,1591484411&fm=253&fmt=auto&app=138?f=JPEG?w=500&h=667",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "xian-tang-dynasty-museum",
    "name": "西安大唐西市博物馆",
    "location": "西安",
    "tags": [
      "唐朝",
      "丝绸之路",
      "商贸"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanchang-august-first-museum",
    "name": "南昌八一起义纪念馆",
    "location": "南昌",
    "tags": [
      "革命历史",
      "军事",
      "红色教育"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhenjiang-museum",
    "name": "镇江博物馆",
    "location": "镇江",
    "tags": [
      "镇江文化",
      "长江文明",
      "山水文化"
    ],
    "image": "https://museumcheck.cn/images/zhenjiang-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "青铜凤纹尊",
        "dynasty": "西周",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/zhenjiang-museum-t1-v1.jpg",
        "description": "西周早期青铜礼器，1976年出土于江苏丹阳司徒西周铜器窑藏。通高34厘米、口径41厘米、重约18公斤。尊腹满饰凤鸟纹，两对大型凤鸟回首展翅，间饰蛙形（或龟形）小动物，纹饰繁丽华贵。是迄今所见吴国早期铸造最精美华丽的青铜重器，镇江博物馆唯一的“国宝级”文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E9%93%9C%E5%87%A4%E7%BA%B9%E5%B0%8A_%EF%BC%88%E6%AD%A3%EF%BC%89.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "白色瑰宝",
        "attribution": "白色瑰宝 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "银鎏金龟负“论语玉烛”酒令筒",
        "dynasty": "唐",
        "category": "金银器",
        "imageUrl": "https://museumcheck.cn/images/zhenjiang-museum-t2-v1.jpg",
        "description": "唐代银器，1982年出土于江苏丹徒丁卯桥唐代金银器窑藏。通体银质鎏金：底座作龟形，龟背托举圆柱形酒筹筒，筒身刻“论语玉烛”四字，筒内盛放50枚鎏金银酒令筹。令辞上半采自《论语》语句，下半对应具体饮酒规定，生动再现唐代宴饮礼俗，是唐代金银工艺与酒文化结合的巅峰之作，列入禁止出境展览文物名录。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Guifu_Lunyu_Yuzhu_Jiuchoutong_-_150725095.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Shallowell",
        "attribution": "Shallowell / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "青铜鸟盖壶",
        "dynasty": "西周",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/zhenjiang-museum-t3-v1.jpg",
        "description": "西周青铜酒器，1982年出土于江苏丹徒大港母子墩西周墓。形体硕大，壶盖塑作展翅欲飞的小鸟，弱化器体的沉重感；壶体以凸宽带纹间隔，饰云形勾连纹与对称乳丁，出土时器内尚存液体。造型生动别致，是吴国青铜器中极具特色的代表作品。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E9%93%9C%E9%B8%9F%E7%9B%96%E5%A3%B6.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "白色瑰宝",
        "attribution": "白色瑰宝 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 3.0",
    "imageCopyrightHolder": "猫猫的日记本",
    "imageAttribution": "猫猫的日记本 / CC BY-SA 3.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3AZhenjiang_Museum_01_2011-10.JPG"
  },
  {
    "id": "xuzhou-museum",
    "name": "徐州博物馆",
    "location": "徐州",
    "tags": [
      "汉代文化",
      "楚汉争霸",
      "彭城文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "qingdao-beer-museum",
    "name": "青岛啤酒博物馆",
    "location": "青岛",
    "tags": [
      "啤酒文化",
      "工业遗产",
      "德式建筑"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhoushan-museum",
    "name": "舟山博物馆",
    "location": "舟山",
    "tags": [
      "海岛文化",
      "观音文化",
      "渔业文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "anqing-museum",
    "name": "安庆博物馆",
    "location": "安庆",
    "tags": [
      "黄梅戏",
      "桐城派",
      "安庆文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-geology-museum",
    "name": "中国地质博物馆",
    "location": "北京",
    "tags": [
      "地质科学",
      "矿物标本",
      "地球历史"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Geological_Museum_of_China.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "lu-xun-museum",
    "name": "鲁迅博物馆",
    "location": "北京",
    "tags": [
      "文学历史",
      "现代文学",
      "鲁迅研究"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jilin-museum",
    "name": "吉林省博物院",
    "location": "长春",
    "tags": [
      "东北文化",
      "满族文化",
      "关东风情"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-aviation-museum",
    "name": "中国航空博物馆",
    "location": "北京",
    "tags": [
      "航空历史",
      "航空技术",
      "国防科技"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-film-museum",
    "name": "中国电影博物馆",
    "location": "北京",
    "tags": [
      "电影历史",
      "影视文化",
      "艺术发展"
    ],
    "image": "",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "prince-kung-mansion",
    "name": "恭王府",
    "location": "北京",
    "tags": [
      "皇家府邸",
      "清代建筑",
      "园林艺术",
      "福文化"
    ],
    "image": "",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "china-tea-museum",
    "name": "中国茶叶博物馆",
    "location": "杭州",
    "tags": [
      "茶文化",
      "传统文化",
      "农业文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-silk-museum",
    "name": "中国丝绸博物馆",
    "location": "杭州",
    "tags": [
      "丝绸文化",
      "纺织技术",
      "工艺美术"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-porcelain-museum",
    "name": "中国陶瓷博物馆",
    "location": "景德镇",
    "tags": [
      "陶瓷文化",
      "工艺美术",
      "传统技艺"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-sports-museum",
    "name": "中国体育博物馆",
    "location": "北京",
    "tags": [
      "体育历史",
      "奥运文化",
      "体育精神"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "china-agriculture-museum",
    "name": "中国农业博物馆",
    "location": "北京",
    "tags": [
      "农业历史",
      "农耕文明",
      "农业科技"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "tsinghua-museum",
    "name": "清华大学艺术博物馆",
    "location": "北京",
    "tags": [
      "大学博物馆",
      "艺术教育",
      "文化传承"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "peking-university-museum",
    "name": "北京大学赛克勒考古与艺术博物馆",
    "location": "北京",
    "tags": [
      "大学博物馆",
      "考古学",
      "艺术研究"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "lanzhou-museum-new",
    "name": "兰州市博物馆",
    "location": "兰州",
    "tags": [
      "金城文化",
      "兰州历史",
      "丝路重镇"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "taiyuan-museum-new",
    "name": "太原市博物馆",
    "location": "太原",
    "tags": [
      "晋阳文化",
      "太原历史",
      "龙城风韵"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-printing-museum",
    "name": "中国印刷博物馆",
    "location": "北京",
    "tags": [
      "印刷文化",
      "四大发明",
      "文化传播"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-science-technology-museum",
    "name": "中国科学技术馆",
    "location": "北京",
    "tags": [
      "科学技术",
      "科普教育",
      "创新发展"
    ],
    "image": "http://eb118-file.cdn.bcebos.com/upload/59c7c8753e8b48f6a6ab0224ed104e0a_2211489826.png?x-bce-process=image/format,f_auto/resize,m_lfit,limit_1,w_500,h_500/quality,q_85",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-women-children-museum",
    "name": "中国妇女儿童博物馆",
    "location": "北京",
    "tags": [
      "妇女发展",
      "儿童成长",
      "社会进步"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-ethnic-museum",
    "name": "中华民族博物院",
    "location": "北京",
    "tags": [
      "民族文化",
      "文化多样性",
      "民族团结"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "china-coal-museum",
    "name": "中国煤炭博物馆",
    "location": "太原",
    "tags": [
      "煤炭工业",
      "能源发展",
      "工业文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "xian-banpo-museum",
    "name": "西安半坡博物馆",
    "location": "西安",
    "tags": [
      "史前文明",
      "考古遗址",
      "原始社会"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "tianjin-natural-history-museum",
    "name": "天津自然博物馆",
    "location": "天津",
    "tags": [
      "自然科学",
      "生物多样性",
      "地球演化"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/%E5%A4%A9%E6%B4%A5%E8%87%AA%E7%84%B6%E5%8D%9A%E7%89%A9%E9%A6%86_-_panoramio.jpg/960px-%E5%A4%A9%E6%B4%A5%E8%87%AA%E7%84%B6%E5%8D%9A%E7%89%A9%E9%A6%86_-_panoramio.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "zhou-enlai-deng-yingchao-memorial",
    "name": "周恩来邓颖超纪念馆",
    "location": "天津",
    "tags": [
      "红色文化",
      "伟人纪念",
      "近代史"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Memorial_to_Zhou_Enlai_and_Deng_Yingchao_4.jpg/960px-Memorial_to_Zhou_Enlai_and_Deng_Yingchao_4.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "wuhan-revolution-museum",
    "name": "武汉革命博物馆",
    "location": "武汉",
    "tags": [
      "革命历史",
      "红色文化",
      "近代史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "suzhou-silk-museum",
    "name": "苏州丝绸博物馆",
    "location": "苏州",
    "tags": [
      "苏绣文化",
      "丝绸工艺",
      "江南文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-water-museum",
    "name": "中国水利博物馆",
    "location": "杭州",
    "tags": [
      "水利工程",
      "治水文化",
      "生态文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "pinghu-museum",
    "name": "平湖市博物馆",
    "location": "平湖",
    "tags": [
      "历史",
      "地方",
      "文化"
    ],
    "image": "https://museumcheck.cn/images/pinghu-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "三级",
    "collections": [
      {
        "name": "明代白玉藕片",
        "dynasty": "明代",
        "category": "玉器",
        "imageUrl": "https://museumcheck.cn/images/pinghu-museum-t1-v1.jpg",
        "description": "平湖市博物馆藏明代白玉藕片，玉雕莲藕造型，寓意「连生贵子」，温润精巧。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jade_Articles_Collected_in_Pinghu_Museum_02_2014-06.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 3.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "明代白玉绞丝镯",
        "dynasty": "明代",
        "category": "玉器",
        "imageUrl": "https://museumcheck.cn/images/pinghu-museum-t2-v1.jpg",
        "description": "平湖市博物馆藏明代白玉绞丝镯，丝环相绞的工艺展现高超碾玉技艺。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jade_Articles_Collected_in_Pinghu_Museum_03_2014-06.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 3.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "清代兵器形玉佩件",
        "dynasty": "清代",
        "category": "玉器",
        "imageUrl": "https://museumcheck.cn/images/pinghu-museum-t3-v1.jpg",
        "description": "平湖市博物馆藏清代兵器形玉佩件，仿刀剑造型的玉佩，别具意趣。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jade_Articles_Collected_in_Pinghu_Museum_04_2014-06.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 3.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 3.0",
    "imageCopyrightHolder": "猫猫的日记本",
    "imageAttribution": "猫猫的日记本 / CC BY-SA 3.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3APinghu_Museum_01_2014-06.JPG"
  },
  {
    "id": "china-archaeology-museum",
    "name": "中国考古博物馆",
    "location": "北京",
    "tags": [
      "考古发现",
      "文明探源",
      "科学研究"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/China_Archaeological_Museum-Exterior-20250227.jpg",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "china-ancient-architecture-museum",
    "name": "北京古代建筑博物馆",
    "location": "北京",
    "tags": [
      "建筑",
      "古代",
      "文化",
      "北京"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/96/North_gate_of_Xiannongtan_and_Beijing_Yucai_School_%2820221001165539%29.jpg",
    "hasCollections": false,
    "level": "二级"
  },
  {
    "id": "beijing-aerospace-museum",
    "name": "北京航空航天博物馆",
    "location": "北京",
    "tags": [
      "航空",
      "航天",
      "科技",
      "历史",
      "军事"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/83/Beijing_Air_and_Space_Museum.jpg",
    "hasCollections": true,
    "level": "未定级"
  },
  {
    "id": "dehua-ceramics-museum",
    "name": "德化县陶瓷博物馆",
    "location": "福建",
    "tags": [
      "陶瓷",
      "艺术",
      "工艺",
      "文化"
    ],
    "image": "https://img2.baidu.com/it/u=4244108941,2042509085&fm=253&fmt=auto&app=138&f=JPEG&w=1067&h=800",
    "hasCollections": true,
    "level": "二级"
  },
  {
    "id": "china-mintaiyuan-museum",
    "name": "中国闽台缘博物馆",
    "location": "福建",
    "tags": [
      "历史",
      "文化",
      "闽台关系",
      "民俗",
      "闽南文化"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Mintaiyuan_Museum.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "quanzhou-intangible-heritage-museum",
    "name": "泉州非物质文化遗产馆",
    "location": "福建",
    "tags": [
      "非物质文化遗产",
      "民俗",
      "文化",
      "传统技艺"
    ],
    "image": "",
    "hasCollections": true,
    "level": "三级"
  },
  {
    "id": "yueyang-museum",
    "name": "岳阳博物馆",
    "location": "岳阳",
    "tags": [
      "历史",
      "青铜器",
      "楚文化",
      "龙舟",
      "湖湘文化"
    ],
    "image": "https://museumcheck.cn/images/building.jpg",
    "hasCollections": true,
    "level": "二级"
  },
  {
    "id": "auckland-war-memorial-museum",
    "name": "奥克兰战争纪念馆",
    "location": "新西兰·奥克兰",
    "tags": [
      "历史",
      "战争纪念",
      "毛利文化",
      "海外博物馆"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/10/Auckland_War_Memorial_Museum.jpg",
    "hasCollections": true,
    "level": "未定级"
  },
  {
    "id": "haining-museum",
    "name": "海宁市博物馆",
    "location": "海宁",
    "tags": [
      "海宁",
      "湖田窑",
      "宋瓷",
      "亲子"
    ],
    "image": "https://museumcheck.cn/images/haining-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "三级",
    "collections": [
      {
        "name": "北宋湖田窑敞口罐",
        "dynasty": "北宋",
        "category": "瓷器",
        "imageUrl": "https://museumcheck.cn/images/haining-museum-t1-v1.jpg",
        "description": "1974年海宁硖石镇东山西麓宋墓出土，北宋景德镇湖田窑青白瓷敞口罐，釉色莹润。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Porcelain_of_Hutian_Ware_in_Haining_Museum_01_2014-08.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "北宋湖田窑注子和温碗",
        "dynasty": "北宋",
        "category": "瓷器",
        "imageUrl": "https://museumcheck.cn/images/haining-museum-t2-v1.jpg",
        "description": "1974年海宁宋墓出土，北宋湖田窑注子（酒壶）与温碗一套，再现宋人注酒温酒之雅。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Porcelain_of_Hutian_Ware_in_Haining_Museum_02_2014-08.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "北宋湖田窑注子和刻花温碗",
        "dynasty": "北宋",
        "category": "瓷器",
        "imageUrl": "https://museumcheck.cn/images/haining-museum-t3-v1.jpg",
        "description": "1974年海宁宋墓出土，北宋湖田窑注子配刻花温碗，青白瓷刻花细腻，宋瓷精品。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Porcelain_of_Hutian_Ware_in_Haining_Museum_03_2014-08.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY-SA 4.0",
    "imageCopyrightHolder": "猫猫的日记本",
    "imageAttribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3AHaining_Museum_01_2014-08.JPG"
  },
  {
    "id": "haiyan-museum",
    "name": "海盐县博物馆",
    "location": "海盐",
    "tags": [
      "海盐",
      "青铜器",
      "佛教文物",
      "亲子"
    ],
    "image": null,
    "hasCollections": true,
    "level": "三级",
    "collections": [
      {
        "name": "象形铜尊",
        "dynasty": "春秋",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/haiyan-museum-t1-v1.jpg",
        "description": "海盐县博物馆藏象形铜尊，仿象形制的青铜盛酒器，造型生动。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elephant-shaped_Bronze_Zun_in_Haiyan_Museum_01_2015-03.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "鎏金铁阿育王塔",
        "dynasty": "五代（吴越国）",
        "category": "佛教文物",
        "imageUrl": "https://museumcheck.cn/images/haiyan-museum-t2-v1.jpg",
        "description": "海盐县博物馆藏鎏金铁阿育王塔，吴越国时期佛教舍利塔，工艺精湛，见证江南崇佛。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gold-Plated_Iron_Asoka_Stupa_in_Haiyan_Museum_01_2015-03.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "狮形铜香炉",
        "dynasty": "明清",
        "category": "铜器",
        "imageUrl": "https://museumcheck.cn/images/haiyan-museum-t3-v1.jpg",
        "description": "海盐县博物馆藏狮形铜香炉，狮钮熏香用具，明清铜器之趣品。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bronze_Lion-shaped_Incense_Burner_in_Haiyan_Museum_01_2015-03.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "猫猫的日记本",
        "attribution": "猫猫的日记本 / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ]
  },
  {
    "id": "nanhu-revolution-museum",
    "name": "南湖革命纪念馆",
    "location": "嘉兴",
    "tags": [
      "嘉兴",
      "南湖",
      "红船",
      "中共一大",
      "革命纪念",
      "亲子"
    ],
    "image": "https://museumcheck.cn/images/nanhu-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "南湖红船（纪念船）",
        "dynasty": "1921年（中共一大闭幕地）",
        "category": "革命纪念船",
        "imageUrl": "https://museumcheck.cn/images/nanhu-museum-t1-v1.jpg",
        "description": "1921年中共一大在上海开幕，后移至嘉兴南湖一艘画舫上继续举行并闭幕，这艘船被誉为“母亲船”。停泊于湖心岛畔的纪念船是红船精神发源地，带孩子来能直观感受建党历史。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E5%8D%97%E6%B9%96%E7%BA%A2%E8%88%B9.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Njzjz",
        "attribution": "Njzjz / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "烟雨楼",
        "dynasty": "始建于五代（现存为清代重建）",
        "category": "江南名楼",
        "imageUrl": "https://museumcheck.cn/images/nanhu-museum-t2-v1.jpg",
        "description": "南湖湖心岛上的江南名楼，乾隆六下江南曾八次登临赋诗。1921年中共一大代表正是在烟雨楼下船、登上红船继续会议，是南湖革命历史空间的核心坐标。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E5%98%89%E5%85%B4%E5%8D%97%E6%B9%96%E7%83%9F%E9%9B%A8%E6%A5%BC_-_panoramio_-_2007-01-01.jpg",
        "rightsType": "CC",
        "license": "CC BY 3.0",
        "copyrightHolder": "江上清风1961",
        "attribution": "江上清风1961 / CC BY 3.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      },
      {
        "name": "南湖湖心岛",
        "dynasty": "南湖核心景区",
        "category": "革命历史空间",
        "imageUrl": "https://museumcheck.cn/images/nanhu-museum-t3-v1.jpg",
        "description": "红船停泊、烟雨楼所在的南湖湖心岛，是中共一大南湖会议的历史现场。登岛漫步，红船与烟雨楼尽收眼底，是亲子红色研学的重要一站。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jiaxing_Lake_island%E5%98%89%E5%85%B4%E6%B9%96%E5%BF%83%E5%B2%9B.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Ddccxl",
        "attribution": "Ddccxl / CC BY-SA 4.0, via Wikimedia Commons",
        "sourceType": "commons-cc"
      }
    ],
    "imageSourceType": "commons-cc",
    "imageLicense": "CC BY 4.0",
    "imageCopyrightHolder": "James2026CN",
    "imageAttribution": "James2026CN / CC BY 4.0, via Wikimedia Commons",
    "imageSourceUrl": "https://commons.wikimedia.org/wiki/File%3A%E5%8D%97%E6%B9%96%E9%9D%A9%E5%91%BD%E7%BA%AA%E5%BF%B5%E9%A6%86%E6%96%B0%E9%A6%86.jpg"
  }
];

// Helper to update cache when this script loads
window.__updateMuseumsMetaCache = function(data) {
  if (window.dataManager) {
    console.log('[museums-meta.js] Loaded ' + data.length + ' museums from meta');
  }
};
