/**
 * Museums Meta Data - Lightweight listing for homepage
 * Auto-generated from data/museums-meta.json
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * To update: modify data/museums-meta.json and run:
 *   node tools/generate-museums-meta-js.js
 * 
 * This file provides lightweight metadata for homepage display.
 * Full museum details (collections, checklists) are loaded dynamically from KV Store.
 */

window.MUSEUMS_META = [
  {
    "id": "forbidden-city",
    "name": "故宫博物院",
    "location": "北京",
    "tags": [
      "历史",
      "建筑",
      "文物"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/00/Sunset_of_the_Forbidden_City_2006.JPG",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "national-museum",
    "name": "中国国家博物馆",
    "location": "北京",
    "tags": [
      "历史",
      "文化",
      "艺术"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/%E4%B8%AD%E5%9B%BD%E5%9B%BD%E5%AE%B6%E5%8D%9A%E7%89%A9%E9%A6%86.JPG",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "shanghai-museum",
    "name": "上海博物馆",
    "location": "上海",
    "tags": [
      "艺术",
      "文物",
      "收藏"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3a/%E4%B8%8A%E6%B5%B7%E5%8D%9A%E7%89%A9%E9%A6%86%E4%B8%9C%E9%A6%86_161003.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shanghai-natural-history-museum",
    "name": "上海自然博物馆",
    "location": "上海",
    "tags": [
      "自然科学",
      "生物多样性",
      "古生物"
    ],
    "image": "",
    "hasCollections": true,
    "level": null
  },
  {
    "id": "terracotta-warriors",
    "name": "秦始皇帝陵博物院",
    "location": "西安",
    "tags": [
      "历史",
      "考古",
      "世界遗产"
    ],
    "image": "https://img0.baidu.com/it/u=394895228,4120900227&fm=253&fmt=auto&app=138?f=JPEG?w=667&h=500",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanjing-museum",
    "name": "南京博物院",
    "location": "南京",
    "tags": [
      "历史",
      "艺术",
      "民俗"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/31/Nanjing_Museum1.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "hubei-museum",
    "name": "湖北省博物馆",
    "location": "武汉",
    "tags": [
      "历史",
      "音乐",
      "青铜器"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Hubei_Provincial_Museum.JPG",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "shaanxi-history",
    "name": "陕西历史博物馆",
    "location": "西安",
    "tags": [
      "历史",
      "文物",
      "古代文明"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/35/%E9%99%95%E8%A5%BF%E5%8E%86%E5%8F%B2%E5%8D%9A%E7%89%A9%E9%A6%86.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "suzhou-museum",
    "name": "苏州博物馆",
    "location": "苏州",
    "tags": [
      "艺术",
      "建筑",
      "江南文化"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Suzhou_Museum_-_new_buildings.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhejiang-museum",
    "name": "浙江省博物馆",
    "location": "杭州",
    "tags": [
      "历史",
      "文化",
      "江南"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d0/%E6%B5%99%E6%B1%9F%E7%9C%81%E5%8D%9A%E7%89%A9%E9%A6%86_-_panoramio.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "guangdong-museum",
    "name": "广东省博物馆",
    "location": "广州",
    "tags": [
      "岭南文化",
      "海丝",
      "文物"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Guangdong_Museum.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "sichuan-museum",
    "name": "四川博物院",
    "location": "成都",
    "tags": [
      "巴蜀文化",
      "历史",
      "民俗"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5f/%E5%9B%9B%E5%B7%9D%E5%8D%9A%E7%89%A9%E9%99%A2.JPG",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "henan-museum",
    "name": "河南博物院",
    "location": "郑州",
    "tags": [
      "中原文化",
      "文物",
      "历史"
    ],
    "image": "https://museumcheck.cn/images/henan-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "妇好鸮尊",
        "dynasty": "商代晚期",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/henan-museum-t1-v1.jpg",
        "description": "1976年安阳殷墟妇好墓出土，通高46.3厘米，鸮（猫头鹰）形青铜盛酒器，中国最早鸟形铜尊之一，河南博物院镇院之宝。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fuhao_Owl_Zun_front.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Cangmin (Wikimedia Commons)",
        "attribution": "Cangmin / CC BY-SA 4.0, via Wikimedia Commons"
      },
      {
        "name": "莲鹤方壶",
        "dynasty": "春秋中期",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/henan-museum-t2-v1.jpg",
        "description": "1923年新郑李家楼郑公大墓出土，高117厘米，壶顶莲瓣盛开、立一振翅仙鹤，郭沫若誉其为'时代精神之象征'；河南博物院与故宫各藏一件。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:河南博物院藏莲鹤方壶.jpg",
        "rightsType": "CC",
        "license": "CC BY 3.0",
        "copyrightHolder": "Greg_kf (Wikimedia Commons)",
        "attribution": "Greg_kf / CC BY 3.0, via Wikimedia Commons"
      },
      {
        "name": "云纹铜禁",
        "dynasty": "春秋中期",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/henan-museum-t3-v1.jpg",
        "description": "1978年淅川下寺楚墓出土，通高28.8厘米，失蜡法铸造的云纹铜禁（承置酒器的案具），中国首批禁止出境展览文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bronze_jin_from_Henan.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 3.0",
        "copyrightHolder": "Greg_kf (Wikimedia Commons)",
        "attribution": "Greg_kf / CC BY-SA 3.0, via Wikimedia Commons"
      }
    ]
  },
  {
    "id": "liaoning-museum",
    "name": "辽宁省博物馆",
    "location": "沈阳",
    "tags": [
      "东北文化",
      "考古",
      "历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shandong-museum",
    "name": "山东博物馆",
    "location": "济南",
    "tags": [
      "齐鲁文化",
      "孔子",
      "历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "tianjin-museum",
    "name": "天津博物馆",
    "location": "天津",
    "tags": [
      "历史",
      "青铜器",
      "书画",
      "瓷器",
      "非遗",
      "天津"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/%E5%A4%A9%E6%B4%A5%E5%8D%9A%E7%89%A9%E9%A6%86.png/960px-%E5%A4%A9%E6%B4%A5%E5%8D%9A%E7%89%A9%E9%A6%86.png",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "china-art-museum",
    "name": "中国美术馆",
    "location": "北京",
    "tags": [
      "美术",
      "艺术",
      "绘画"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "tibet-museum",
    "name": "西藏博物馆",
    "location": "拉萨",
    "tags": [
      "藏族文化",
      "雪域高原",
      "佛教"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "xinjiang-museum",
    "name": "新疆维吾尔自治区博物馆",
    "location": "乌鲁木齐",
    "tags": [
      "丝绸之路",
      "多民族",
      "西域文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yunnan-museum",
    "name": "云南省博物馆",
    "location": "昆明",
    "tags": [
      "多民族",
      "西南文化",
      "边疆历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "inner-mongolia-museum",
    "name": "内蒙古博物院",
    "location": "呼和浩特",
    "tags": [
      "草原文化",
      "蒙古族",
      "游牧文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "chongqing-three-gorges-museum",
    "name": "重庆中国三峡博物馆",
    "location": "重庆",
    "tags": [
      "三峡文化",
      "巴渝文化",
      "山城历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "qinghai-museum",
    "name": "青海省博物馆",
    "location": "西宁",
    "tags": [
      "青藏高原",
      "多民族",
      "高原文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "heilongjiang-museum",
    "name": "黑龙江省博物馆",
    "location": "哈尔滨",
    "tags": [
      "东北文化",
      "中俄交流",
      "近代史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-capital-museum",
    "name": "首都博物馆",
    "location": "北京",
    "tags": [
      "北京历史",
      "古都文化",
      "民俗"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/36/Capital_Museum_in_Beijing.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-military-museum",
    "name": "中国人民革命军事博物馆",
    "location": "北京",
    "tags": [
      "军事历史",
      "革命历史",
      "国防教育"
    ],
    "image": "https://img1.baidu.com/it/u=4286222987,673276445&fm=253&fmt=auto&app=138?f=JPEG?w=800&h=1067",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-natural-history-museum",
    "name": "国家自然博物馆",
    "location": "北京",
    "tags": [
      "自然科学",
      "生物进化",
      "古生物"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Beijing_Museum_of_Natural_History_2.jpg",
    "hasCollections": true,
    "level": null
  },
  {
    "id": "china-railway-museum",
    "name": "中国铁道博物馆",
    "location": "北京",
    "tags": [
      "铁路历史",
      "交通运输",
      "工业发展"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-planetarium",
    "name": "北京天文馆",
    "location": "北京",
    "tags": [
      "天文科学",
      "宇宙探索",
      "科普教育"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Beijing_Planetarium_%2820221112164636%29.jpg/1280px-Beijing_Planetarium_%2820221112164636%29.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "shanghai-science-technology-museum",
    "name": "上海科技馆",
    "location": "上海",
    "tags": [
      "科技创新",
      "科学教育",
      "互动体验"
    ],
    "image": "https://eb118-file.cdn.bcebos.com/upload/6db2b79d9fe34f46b8dbc022a2a09a14_1275921381.png?x-bce-process=image/format,f_auto/resize,m_lfit,limit_1,w_500,h_500/quality,q_85&",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "guangzhou-museum",
    "name": "广州博物馆",
    "location": "广州",
    "tags": [
      "岭南文化",
      "广州历史",
      "海上丝绸之路"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shenzhen-museum",
    "name": "深圳博物馆",
    "location": "深圳",
    "tags": [
      "改革开放",
      "城市发展",
      "现代化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "xian-museum",
    "name": "西安博物院",
    "location": "西安",
    "tags": [
      "古都文化",
      "丝绸之路",
      "唐文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "chengdu-jinsha-museum",
    "name": "成都金沙遗址博物馆",
    "location": "成都",
    "tags": [
      "古蜀文明",
      "考古发现",
      "金沙文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanjing-massacre-memorial",
    "name": "侵华日军南京大屠杀遇难同胞纪念馆",
    "location": "南京",
    "tags": [
      "历史教育",
      "爱国主义",
      "和平教育"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "hangzhou-museum",
    "name": "杭州博物馆",
    "location": "杭州",
    "tags": [
      "西湖文化",
      "江南文化",
      "杭州历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "ningbo-museum",
    "name": "宁波博物馆",
    "location": "宁波",
    "tags": [
      "海洋文化",
      "港口贸易",
      "商业历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "wuxi-museum",
    "name": "无锡博物院",
    "location": "无锡",
    "tags": [
      "江南文化",
      "水乡文化",
      "民族工业"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "changzhou-museum",
    "name": "常州博物馆",
    "location": "常州",
    "tags": [
      "常州历史",
      "江南文化",
      "现代发展"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yangzhou-museum",
    "name": "扬州博物馆",
    "location": "扬州",
    "tags": [
      "运河文化",
      "盐商文化",
      "园林艺术"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "hefei-museum",
    "name": "安徽博物院",
    "location": "合肥",
    "tags": [
      "徽文化",
      "安徽历史",
      "新安文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanchang-museum",
    "name": "江西省博物馆",
    "location": "南昌",
    "tags": [
      "赣文化",
      "江西历史",
      "陶瓷文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jinan-museum",
    "name": "济南市博物馆",
    "location": "济南",
    "tags": [
      "泉城文化",
      "齐鲁文化",
      "济南历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "qingdao-museum",
    "name": "青岛市博物馆",
    "location": "青岛",
    "tags": [
      "海洋文化",
      "青岛历史",
      "近代建筑"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhengzhou-museum",
    "name": "郑州博物馆",
    "location": "郑州",
    "tags": [
      "中原文化",
      "商代文明",
      "黄河文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "wuhan-museum",
    "name": "武汉博物馆",
    "location": "武汉",
    "tags": [
      "荆楚文化",
      "武汉历史",
      "长江文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "kunming-museum",
    "name": "昆明市博物馆",
    "location": "昆明",
    "tags": [
      "滇文化",
      "民族文化",
      "春城文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "guiyang-museum",
    "name": "贵州省博物馆",
    "location": "贵阳",
    "tags": [
      "多民族文化",
      "贵州历史",
      "山地文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "fuzhou-museum",
    "name": "福建博物院",
    "location": "福州",
    "tags": [
      "闽文化",
      "海洋文化",
      "侨乡文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanning-museum",
    "name": "广西壮族自治区博物馆",
    "location": "南宁",
    "tags": [
      "壮族文化",
      "民族文化",
      "桂文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "haikou-museum",
    "name": "海南省博物馆",
    "location": "海口",
    "tags": [
      "海岛文化",
      "热带文化",
      "海南历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shijiazhuang-museum",
    "name": "河北博物院",
    "location": "石家庄",
    "tags": [
      "燕赵文化",
      "河北历史",
      "中山国"
    ],
    "image": "https://museumcheck.cn/images/shijiazhuang-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "长信宫灯",
        "dynasty": "西汉",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/shijiazhuang-museum-t1-v1.jpg",
        "description": "西汉青铜器，1968年河北满城窦绾墓出土，高48厘米，通体鎏金。作跪地执灯宫女形：灯盘可转动，灯罩屏板可推合以调节亮度与照射方向；宫女右臂中空为烟道，烟灰经衣袖进入体中以保持室内清洁。灯分头、身、右臂、灯座、灯盘、灯罩六部分，均可拆卸清洗，灯体刻“长信尚浴”“阳信家”等铭文65字。被誉为“中华第一灯”，2002年列入首批禁止出境展览文物名录，河北博物院“镇馆之宝”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%95%BF%E4%BF%A1%E5%AE%AB%E7%81%AF-%E6%B2%B3%E5%8C%97%E5%8D%9A%E7%89%A9%E9%99%A2.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Suginami",
        "attribution": "Suginami / CC BY-SA 4.0, via Wikimedia Commons"
      },
      {
        "name": "刘胜金缕玉衣",
        "dynasty": "西汉",
        "category": "玉器",
        "imageUrl": "https://museumcheck.cn/images/shijiazhuang-museum-t2-v1.jpg",
        "description": "西汉玉衣，1968年河北满城汉墓（中山靖王刘胜墓）出土。由2498片玉片、约1100克金丝编缀而成，是我国考古发掘中年代最早、保存最完整、规格最高的汉代金缕玉衣，再现了汉代诸侯王丧葬礼制与玉作工艺的巅峰。2002年列入首批禁止出境展览文物名录，河北博物院“镇馆之宝”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jade_burial_suit_of_Liu_Sheng.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Baomi",
        "attribution": "Baomi / CC BY-SA 4.0, via Wikimedia Commons"
      },
      {
        "name": "错金银四龙四凤铜方案座",
        "dynasty": "战国",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/shijiazhuang-museum-t3-v1.jpg",
        "description": "战国青铜器，1977年河北平山三汲村中山王墓出土。案面已朽，仅存案座，边长47.5厘米。底部两雄两雌跪鹿承托，四龙四凤盘绕纠结组成案身：四龙独首双尾上托斗拱，四凤双翅聚于中央连成半球，凤头自龙尾引颈而出。集铸造、镶嵌、焊接等多种工艺于一身，复杂精巧，是战国中山国青铜工艺的代表作，河北博物院“十大珍宝”之一（首批禁止出境展览文物）。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bronze_Square_Table_Stand_Decorated_with_Dragon-and-phoenix.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Photographed by Baomi",
        "attribution": "Photographed by Baomi / CC BY-SA 4.0, via Wikimedia Commons"
      }
    ]
  },
  {
    "id": "taiyuan-museum",
    "name": "山西博物院",
    "location": "太原",
    "tags": [
      "晋文化",
      "煤炭文化",
      "古建筑"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "hohhot-museum",
    "name": "内蒙古自然博物馆",
    "location": "呼和浩特",
    "tags": [
      "草原文化",
      "自然生态",
      "蒙古族文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "lanzhou-museum",
    "name": "甘肃省博物馆",
    "location": "兰州",
    "tags": [
      "丝路文化",
      "马踏飞燕",
      "敦煌文化"
    ],
    "image": "https://museumcheck.cn/images/lanzhou-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "铜奔马（马踏飞燕）",
        "dynasty": "东汉",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/lanzhou-museum-t1-v1.jpg",
        "description": "东汉青铜器，1969年出土于甘肃武威雷台汉墓。通高34.5厘米、长45厘米、宽13.1厘米、重7.3千克。作骏马昂首嘶鸣、疾足奔驰状，三足腾空，一足踏掠飞鸟（燕），摄取奔马超越飞鸟的一瞬；全身着力点集注于踏鸟一足之上，精确掌握力学平衡原理，工艺卓绝。1983年被确定为中国旅游标志，1986年鉴定为国宝级文物，2002年列入首批禁止出境展览文物名录，是丝绸之路精神的象征、甘肃省博物馆“镇馆之宝”。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%9B%B7%E5%8F%B0%E6%B1%89%E5%A2%93%E9%93%9C%E5%A5%94%E9%A9%AC3.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "三猎",
        "attribution": "三猎 / CC BY-SA 4.0, via Wikimedia Commons"
      },
      {
        "name": "人头形器口彩陶瓶",
        "dynasty": "新石器时代（仰韶文化）",
        "category": "彩陶",
        "imageUrl": "https://museumcheck.cn/images/lanzhou-museum-t2-v1.jpg",
        "description": "仰韶文化中期（庙底沟类型）彩陶，1973年出土于甘肃秦安大地湾遗址。高32.3厘米、口径4厘米、底径6.8厘米，细泥红陶质地。瓶口雕塑为圆雕人头像：挺鼻小嘴、齐刘海、双耳有系挂饰物小孔；瓶身绘黑彩弧线三角纹与变体鸟纹。是大地湾出土上千件陶器中唯一塑有人像的彩陶瓶，将人头与葫芦瓶巧妙结合，体现先民对自身力量的认识与艺术再现能力。2013年列入第三批禁止出境展览文物名录。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E4%BB%B0%E9%9F%B6%E6%96%87%E5%8C%96%E4%BA%BA%E5%A4%B4%E5%BD%A2%E5%99%A8%E5%8F%A3%E5%BD%A9%E9%99%B6%E7%93%B6.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "三猎",
        "attribution": "三猎 / CC BY-SA 4.0, via Wikimedia Commons"
      },
      {
        "name": "莲花玻璃托盏",
        "dynasty": "元",
        "category": "玻璃器",
        "imageUrl": "https://museumcheck.cn/images/lanzhou-museum-t3-v1.jpg",
        "description": "元代玻璃器，出土于甘肃漳县汪世显家族墓。一托一盏，通体半透明蓝色玻璃质，仿莲花造型——托如莲叶，盏似盛开的莲花，是国内迄今出土最完整的一套元代玻璃托盏。造型清丽、工艺精巧，反映了元代玻璃制造工艺的高超水平，是甘肃省博物馆馆藏精品。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yuan_Lotus-shaped_Glass_Calix_(10096176946).jpg",
        "rightsType": "CC",
        "license": "CC0",
        "copyrightHolder": "Gary Todd",
        "attribution": "Gary Todd / CC0, via Wikimedia Commons"
      }
    ]
  },
  {
    "id": "xining-museum",
    "name": "青海藏医药文化博物馆",
    "location": "西宁",
    "tags": [
      "藏医药",
      "高原文化",
      "民族医学"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yantai-museum",
    "name": "烟台市博物馆",
    "location": "烟台",
    "tags": [
      "胶东文化",
      "海洋文化",
      "近代开埠"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "linyi-museum",
    "name": "临沂市博物馆",
    "location": "临沂",
    "tags": [
      "沂蒙文化",
      "革命文化",
      "临沂历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "wenzhou-museum",
    "name": "温州博物馆",
    "location": "温州",
    "tags": [
      "瓯越文化",
      "商业文化",
      "温州历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shaoxing-museum",
    "name": "绍兴博物馆",
    "location": "绍兴",
    "tags": [
      "水乡文化",
      "越文化",
      "文人文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jiaxing-museum",
    "name": "嘉兴博物馆",
    "location": "嘉兴",
    "tags": [
      "红船精神",
      "江南文化",
      "嘉兴历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jingdezhen-museum",
    "name": "景德镇中国陶瓷博物馆",
    "location": "景德镇",
    "tags": [
      "陶瓷文化",
      "制瓷工艺",
      "瓷都文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "quanzhou-museum",
    "name": "泉州海外交通史博物馆",
    "location": "泉州",
    "tags": [
      "海上丝绸之路",
      "海外交通",
      "泉州文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "quanzhou-huaqiao-museum",
    "name": "泉州华侨历史博物馆",
    "location": "泉州",
    "tags": [
      "华侨历史",
      "文化遗产",
      "泉州文化",
      "海外华人",
      "历史"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/dd/%E6%B3%89%E5%B7%9E%E5%8D%8E%E4%BE%A8%E5%8E%86%E5%8F%B2%E5%8D%9A%E7%89%A9%E9%A6%86.jpg",
    "hasCollections": true,
    "level": "三级"
  },
  {
    "id": "quanzhou-city-museum",
    "name": "泉州博物馆",
    "location": "泉州",
    "tags": [
      "历史",
      "文化",
      "闽南文化",
      "考古",
      "海丝文化"
    ],
    "image": "https://img2.baidu.com/it/u=3862590014,3235502598&fm=253&fmt=auto&app=138&f=JPEG&w=889&h=500",
    "hasCollections": false,
    "level": "二级"
  },
  {
    "id": "xiamen-museum",
    "name": "厦门市博物馆",
    "location": "厦门",
    "tags": [
      "闽南文化",
      "侨乡文化",
      "海岛文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jiangmen-museum",
    "name": "江门市博物馆",
    "location": "江门",
    "tags": [
      "侨乡文化",
      "碉楼文化",
      "江门历史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "baotou-museum",
    "name": "包头博物馆",
    "location": "包头",
    "tags": [
      "工业文化",
      "草原文化",
      "钢铁文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "yichang-museum",
    "name": "宜昌博物馆",
    "location": "宜昌",
    "tags": [
      "三峡文化",
      "长江文明",
      "水利文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "luoyang-museum",
    "name": "洛阳博物馆",
    "location": "洛阳",
    "tags": [
      "古都文化",
      "洛阳历史",
      "牡丹文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jingzhou-museum",
    "name": "荆州博物馆",
    "location": "荆州",
    "tags": [
      "楚文化",
      "历史名城",
      "文物考古"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "guilin-museum",
    "name": "桂林博物馆",
    "location": "桂林",
    "tags": [
      "山水文化",
      "桂北文化",
      "世界遗产"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jian-museum",
    "name": "吉安市博物馆",
    "location": "吉安",
    "tags": [
      "庐陵文化",
      "吉安历史",
      "书院文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "shangrao-museum",
    "name": "上饶市博物馆",
    "location": "上饶",
    "tags": [
      "赣东北文化",
      "上饶历史",
      "生态文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "ganzhou-museum",
    "name": "赣州市博物馆",
    "location": "赣州",
    "tags": [
      "客家文化",
      "赣州历史",
      "宋城文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jiujiang-museum",
    "name": "九江市博物馆",
    "location": "九江",
    "tags": [
      "庐山文化",
      "九江历史",
      "长江文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "beijing-art-museum",
    "name": "北京艺术博物馆",
    "location": "北京",
    "tags": [
      "艺术",
      "绘画",
      "雕塞"
    ],
    "image": "https://img1.baidu.com/it/u=486738805,1591484411&fm=253&fmt=auto&app=138?f=JPEG?w=500&h=667",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "xian-tang-dynasty-museum",
    "name": "西安大唐西市博物馆",
    "location": "西安",
    "tags": [
      "唐朝",
      "丝绸之路",
      "商贸"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "nanchang-august-first-museum",
    "name": "南昌八一起义纪念馆",
    "location": "南昌",
    "tags": [
      "革命历史",
      "军事",
      "红色教育"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhenjiang-museum",
    "name": "镇江博物馆",
    "location": "镇江",
    "tags": [
      "镇江文化",
      "长江文明",
      "山水文化"
    ],
    "image": "https://museumcheck.cn/images/zhenjiang-museum-photo-v1.jpg",
    "hasCollections": true,
    "level": "一级",
    "collections": [
      {
        "name": "青铜凤纹尊",
        "dynasty": "西周",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/zhenjiang-museum-t1-v1.jpg",
        "description": "西周早期青铜礼器，1976年出土于江苏丹阳司徒西周铜器窑藏。通高34厘米、口径41厘米、重约18公斤。尊腹满饰凤鸟纹，两对大型凤鸟回首展翅，间饰蛙形（或龟形）小动物，纹饰繁丽华贵。是迄今所见吴国早期铸造最精美华丽的青铜重器，镇江博物馆唯一的“国宝级”文物。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E9%93%9C%E5%87%A4%E7%BA%B9%E5%B0%8A_%EF%BC%88%E6%AD%A3%EF%BC%89.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "白色瑰宝",
        "attribution": "白色瑰宝 / CC BY-SA 4.0, via Wikimedia Commons"
      },
      {
        "name": "银鎏金龟负“论语玉烛”酒令筒",
        "dynasty": "唐",
        "category": "金银器",
        "imageUrl": "https://museumcheck.cn/images/zhenjiang-museum-t2-v1.jpg",
        "description": "唐代银器，1982年出土于江苏丹徒丁卯桥唐代金银器窑藏。通体银质鎏金：底座作龟形，龟背托举圆柱形酒筹筒，筒身刻“论语玉烛”四字，筒内盛放50枚鎏金银酒令筹。令辞上半采自《论语》语句，下半对应具体饮酒规定，生动再现唐代宴饮礼俗，是唐代金银工艺与酒文化结合的巅峰之作，列入禁止出境展览文物名录。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Guifu_Lunyu_Yuzhu_Jiuchoutong_-_150725095.JPG",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "Shallowell",
        "attribution": "Shallowell / CC BY-SA 4.0, via Wikimedia Commons"
      },
      {
        "name": "青铜鸟盖壶",
        "dynasty": "西周",
        "category": "青铜器",
        "imageUrl": "https://museumcheck.cn/images/zhenjiang-museum-t3-v1.jpg",
        "description": "西周青铜酒器，1982年出土于江苏丹徒大港母子墩西周墓。形体硕大，壶盖塑作展翅欲飞的小鸟，弱化器体的沉重感；壶体以凸宽带纹间隔，饰云形勾连纹与对称乳丁，出土时器内尚存液体。造型生动别致，是吴国青铜器中极具特色的代表作品。",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E9%93%9C%E9%B8%9F%E7%9B%96%E5%A3%B6.jpg",
        "rightsType": "CC",
        "license": "CC BY-SA 4.0",
        "copyrightHolder": "白色瑰宝",
        "attribution": "白色瑰宝 / CC BY-SA 4.0, via Wikimedia Commons"
      }
    ]
  },
  {
    "id": "xuzhou-museum",
    "name": "徐州博物馆",
    "location": "徐州",
    "tags": [
      "汉代文化",
      "楚汉争霸",
      "彭城文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "qingdao-beer-museum",
    "name": "青岛啤酒博物馆",
    "location": "青岛",
    "tags": [
      "啤酒文化",
      "工业遗产",
      "德式建筑"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "zhoushan-museum",
    "name": "舟山博物馆",
    "location": "舟山",
    "tags": [
      "海岛文化",
      "观音文化",
      "渔业文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "anqing-museum",
    "name": "安庆博物馆",
    "location": "安庆",
    "tags": [
      "黄梅戏",
      "桐城派",
      "安庆文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-geology-museum",
    "name": "中国地质博物馆",
    "location": "北京",
    "tags": [
      "地质科学",
      "矿物标本",
      "地球历史"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Geological_Museum_of_China.jpg",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "lu-xun-museum",
    "name": "鲁迅博物馆",
    "location": "北京",
    "tags": [
      "文学历史",
      "现代文学",
      "鲁迅研究"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "jilin-museum",
    "name": "吉林省博物院",
    "location": "长春",
    "tags": [
      "东北文化",
      "满族文化",
      "关东风情"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-aviation-museum",
    "name": "中国航空博物馆",
    "location": "北京",
    "tags": [
      "航空历史",
      "航空技术",
      "国防科技"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-film-museum",
    "name": "中国电影博物馆",
    "location": "北京",
    "tags": [
      "电影历史",
      "影视文化",
      "艺术发展"
    ],
    "image": "",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "prince-kung-mansion",
    "name": "恭王府",
    "location": "北京",
    "tags": [
      "皇家府邸",
      "清代建筑",
      "园林艺术",
      "福文化"
    ],
    "image": "",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "china-tea-museum",
    "name": "中国茶叶博物馆",
    "location": "杭州",
    "tags": [
      "茶文化",
      "传统文化",
      "农业文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-silk-museum",
    "name": "中国丝绸博物馆",
    "location": "杭州",
    "tags": [
      "丝绸文化",
      "纺织技术",
      "工艺美术"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-porcelain-museum",
    "name": "中国陶瓷博物馆",
    "location": "景德镇",
    "tags": [
      "陶瓷文化",
      "工艺美术",
      "传统技艺"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-sports-museum",
    "name": "中国体育博物馆",
    "location": "北京",
    "tags": [
      "体育历史",
      "奥运文化",
      "体育精神"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "china-agriculture-museum",
    "name": "中国农业博物馆",
    "location": "北京",
    "tags": [
      "农业历史",
      "农耕文明",
      "农业科技"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "tsinghua-museum",
    "name": "清华大学艺术博物馆",
    "location": "北京",
    "tags": [
      "大学博物馆",
      "艺术教育",
      "文化传承"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "peking-university-museum",
    "name": "北京大学赛克勒考古与艺术博物馆",
    "location": "北京",
    "tags": [
      "大学博物馆",
      "考古学",
      "艺术研究"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "lanzhou-museum-new",
    "name": "兰州市博物馆",
    "location": "兰州",
    "tags": [
      "金城文化",
      "兰州历史",
      "丝路重镇"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "taiyuan-museum-new",
    "name": "太原市博物馆",
    "location": "太原",
    "tags": [
      "晋阳文化",
      "太原历史",
      "龙城风韵"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-printing-museum",
    "name": "中国印刷博物馆",
    "location": "北京",
    "tags": [
      "印刷文化",
      "四大发明",
      "文化传播"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-science-technology-museum",
    "name": "中国科学技术馆",
    "location": "北京",
    "tags": [
      "科学技术",
      "科普教育",
      "创新发展"
    ],
    "image": "http://eb118-file.cdn.bcebos.com/upload/59c7c8753e8b48f6a6ab0224ed104e0a_2211489826.png?x-bce-process=image/format,f_auto/resize,m_lfit,limit_1,w_500,h_500/quality,q_85",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-women-children-museum",
    "name": "中国妇女儿童博物馆",
    "location": "北京",
    "tags": [
      "妇女发展",
      "儿童成长",
      "社会进步"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-ethnic-museum",
    "name": "中华民族博物院",
    "location": "北京",
    "tags": [
      "民族文化",
      "文化多样性",
      "民族团结"
    ],
    "image": "",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "china-coal-museum",
    "name": "中国煤炭博物馆",
    "location": "太原",
    "tags": [
      "煤炭工业",
      "能源发展",
      "工业文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "xian-banpo-museum",
    "name": "西安半坡博物馆",
    "location": "西安",
    "tags": [
      "史前文明",
      "考古遗址",
      "原始社会"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "tianjin-natural-history-museum",
    "name": "天津自然博物馆",
    "location": "天津",
    "tags": [
      "自然科学",
      "生物多样性",
      "地球演化"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/%E5%A4%A9%E6%B4%A5%E8%87%AA%E7%84%B6%E5%8D%9A%E7%89%A9%E9%A6%86_-_panoramio.jpg/960px-%E5%A4%A9%E6%B4%A5%E8%87%AA%E7%84%B6%E5%8D%9A%E7%89%A9%E9%A6%86_-_panoramio.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "zhou-enlai-deng-yingchao-memorial",
    "name": "周恩来邓颖超纪念馆",
    "location": "天津",
    "tags": [
      "红色文化",
      "伟人纪念",
      "近代史"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Memorial_to_Zhou_Enlai_and_Deng_Yingchao_4.jpg/960px-Memorial_to_Zhou_Enlai_and_Deng_Yingchao_4.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "wuhan-revolution-museum",
    "name": "武汉革命博物馆",
    "location": "武汉",
    "tags": [
      "革命历史",
      "红色文化",
      "近代史"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "suzhou-silk-museum",
    "name": "苏州丝绸博物馆",
    "location": "苏州",
    "tags": [
      "苏绣文化",
      "丝绸工艺",
      "江南文化"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "china-water-museum",
    "name": "中国水利博物馆",
    "location": "杭州",
    "tags": [
      "水利工程",
      "治水文化",
      "生态文明"
    ],
    "image": "",
    "hasCollections": false,
    "level": "一级"
  },
  {
    "id": "pinghu-museum",
    "name": "平湖市博物馆",
    "location": "平湖",
    "tags": [
      "历史",
      "地方",
      "文化"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/92/Pinghu_Museum_02_2014-06.JPG",
    "hasCollections": false,
    "level": "三级"
  },
  {
    "id": "china-archaeology-museum",
    "name": "中国考古博物馆",
    "location": "北京",
    "tags": [
      "考古发现",
      "文明探源",
      "科学研究"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/China_Archaeological_Museum-Exterior-20250227.jpg",
    "hasCollections": false,
    "level": "未定级"
  },
  {
    "id": "china-ancient-architecture-museum",
    "name": "北京古代建筑博物馆",
    "location": "北京",
    "tags": [
      "建筑",
      "古代",
      "文化",
      "北京"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/96/North_gate_of_Xiannongtan_and_Beijing_Yucai_School_%2820221001165539%29.jpg",
    "hasCollections": false,
    "level": "二级"
  },
  {
    "id": "beijing-aerospace-museum",
    "name": "北京航空航天博物馆",
    "location": "北京",
    "tags": [
      "航空",
      "航天",
      "科技",
      "历史",
      "军事"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/83/Beijing_Air_and_Space_Museum.jpg",
    "hasCollections": true,
    "level": "未定级"
  },
  {
    "id": "dehua-ceramics-museum",
    "name": "德化县陶瓷博物馆",
    "location": "福建",
    "tags": [
      "陶瓷",
      "艺术",
      "工艺",
      "文化"
    ],
    "image": "https://img2.baidu.com/it/u=4244108941,2042509085&fm=253&fmt=auto&app=138&f=JPEG&w=1067&h=800",
    "hasCollections": true,
    "level": "二级"
  },
  {
    "id": "china-mintaiyuan-museum",
    "name": "中国闽台缘博物馆",
    "location": "福建",
    "tags": [
      "历史",
      "文化",
      "闽台关系",
      "民俗",
      "闽南文化"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Mintaiyuan_Museum.jpg",
    "hasCollections": true,
    "level": "一级"
  },
  {
    "id": "quanzhou-intangible-heritage-museum",
    "name": "泉州非物质文化遗产馆",
    "location": "福建",
    "tags": [
      "非物质文化遗产",
      "民俗",
      "文化",
      "传统技艺"
    ],
    "image": "",
    "hasCollections": true,
    "level": "三级"
  },
  {
    "id": "yueyang-museum",
    "name": "岳阳博物馆",
    "location": "岳阳",
    "tags": [
      "历史",
      "青铜器",
      "楚文化",
      "龙舟",
      "湖湘文化"
    ],
    "image": "https://museumcheck.cn/images/building.jpg",
    "hasCollections": true,
    "level": "二级"
  },
  {
    "id": "auckland-war-memorial-museum",
    "name": "奥克兰战争纪念馆",
    "location": "新西兰·奥克兰",
    "tags": [
      "历史",
      "战争纪念",
      "毛利文化",
      "海外博物馆"
    ],
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/10/Auckland_War_Memorial_Museum.jpg",
    "hasCollections": true,
    "level": "未定级"
  }
];

// Helper to update cache when this script loads
window.__updateMuseumsMetaCache = function(data) {
  if (window.dataManager) {
    console.log('[museums-meta.js] Loaded ' + data.length + ' museums from meta');
  }
};
